<?php

namespace Proxies\__CG__\Stocks\AchatBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Demande extends \Stocks\AchatBundle\Entity\Demande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'id', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'numDemande', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'objetDemande', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'dateEmission', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'adresseLivraison', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'nomEmetteur');
        }

        return array('__isInitialized__', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'id', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'numDemande', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'objetDemande', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'dateEmission', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'adresseLivraison', '' . "\0" . 'Stocks\\AchatBundle\\Entity\\Demande' . "\0" . 'nomEmetteur');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Demande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumDemande($numDemande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumDemande', array($numDemande));

        return parent::setNumDemande($numDemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumDemande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumDemande', array());

        return parent::getNumDemande();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjetDemande($objetDemande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjetDemande', array($objetDemande));

        return parent::setObjetDemande($objetDemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjetDemande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjetDemande', array());

        return parent::getObjetDemande();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEmission($dateEmission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEmission', array($dateEmission));

        return parent::setDateEmission($dateEmission);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEmission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEmission', array());

        return parent::getDateEmission();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseLivraison($adresseLivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseLivraison', array($adresseLivraison));

        return parent::setAdresseLivraison($adresseLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseLivraison', array());

        return parent::getAdresseLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomEmetteur($nomEmetteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomEmetteur', array($nomEmetteur));

        return parent::setNomEmetteur($nomEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomEmetteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomEmetteur', array());

        return parent::getNomEmetteur();
    }

}
